services:
  - type: web
    name: viral-video-chopper
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install -r requirements.txt &&
      wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz &&
      tar xvf ffmpeg-release-amd64-static.tar.xz &&
      mv ffmpeg-*-amd64-static/ffmpeg /opt/render/project/src/ &&
      mv ffmpeg-*-amd64-static/ffprobe /opt/render/project/src/ &&
      chmod +x ffmpeg ffprobe
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PATH
        value: /opt/render/project/src:$PATH